export type {
  FTAttributes,
  FTAutoTrackingConfig,
  FTCocosConfig,
  FTCocosEnterOptions,
  FTCocosHybridConfig,
  FTEnvironment,
  FTHybridSessionReplayConfig,
  FTLoggerConfig,
  FTLogLevel,
  FTPrimitive,
  FTReplayImagePolicy,
  FTReplayPrivacyMode,
  FTReplayQuality,
  FTReplayTouchPrivacy,
  FTResourceContent,
  FTResourceMetrics,
  FTRUMConfig,
  FTSDKConfig,
  FTSessionReplayConfig,
  FTTraceConfig,
  FTTraceType,
  FTUserData,
  FTValue,
} from './types.js';

export { FT_COCOS_SDK_VERSION } from './version.js';
