import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const environmentKeys = [
  'SAMPLE_DATAKIT_URL',
  'SAMPLE_DATAWAY_URL',
  'SAMPLE_CLIENT_TOKEN',
  'SAMPLE_ANDROID_APP_ID',
  'SAMPLE_IOS_APP_ID',
  'SAMPLE_SERVICE_NAME',
  'SAMPLE_ENV',
  'SAMPLE_DEBUG',
];

const outputRoot = path.resolve(readOption('--output-root') || process.cwd());
const nativeHostDirectory = readRelativeDirectoryOption('--native-host-dir', 'examples/hybrid-creator3/native-host');
const configuration = readConfiguration(process.env);
const targets = [
  {
    path: path.join(nativeHostDirectory, 'android/HybridSampleEnvironment.java'),
    source: renderAndroidConfiguration(configuration),
  },
  {
    path: path.join(nativeHostDirectory, 'ios/HybridSampleEnvironment.generated.h'),
    source: renderIOSConfiguration(configuration),
  },
];

await Promise.all(targets.map(async (target) => {
  const destination = path.join(outputRoot, target.path);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, target.source);
}));

process.stdout.write(`Generated ${targets.length} ignored native-host Sample configuration files from environment variables.\n`);

function readConfiguration(environment) {
  const values = Object.fromEntries(environmentKeys.map((key) => [key, optional(environment[key])]));
  const datakitUrl = values.SAMPLE_DATAKIT_URL;
  const datawayUrl = values.SAMPLE_DATAWAY_URL;
  const clientToken = values.SAMPLE_CLIENT_TOKEN;

  if (datakitUrl && (datawayUrl || clientToken)) {
    fail('Set SAMPLE_DATAKIT_URL or SAMPLE_DATAWAY_URL with SAMPLE_CLIENT_TOKEN, not both.');
  }
  if (!datakitUrl && !(datawayUrl && clientToken)) {
    fail('Set SAMPLE_DATAKIT_URL or both SAMPLE_DATAWAY_URL and SAMPLE_CLIENT_TOKEN.');
  }
  if (Boolean(datawayUrl) !== Boolean(clientToken)) {
    fail('SAMPLE_DATAWAY_URL and SAMPLE_CLIENT_TOKEN must be set together.');
  }

  const androidAppId = values.SAMPLE_ANDROID_APP_ID;
  const iosAppId = values.SAMPLE_IOS_APP_ID;
  if (!androidAppId && !iosAppId) {
    fail('Set SAMPLE_ANDROID_APP_ID, SAMPLE_IOS_APP_ID, or both.');
  }

  return {
    datakitUrl,
    datawayUrl,
    clientToken,
    androidAppId,
    iosAppId,
    debug: parseBoolean(values.SAMPLE_DEBUG, true),
    serviceName: values.SAMPLE_SERVICE_NAME || 'cocos-hybrid-sample',
    env: values.SAMPLE_ENV || 'demo',
  };
}

function renderAndroidConfiguration(configuration) {
  return [
    '// Generated by npm run sample:configure. Contains local credentials; do not commit.',
    'package com.truewatch.cocos.sample;',
    '',
    'final class HybridSampleEnvironment {',
    `    static final String DATAKIT_URL = ${javaString(configuration.datakitUrl)};`,
    `    static final String DATAWAY_URL = ${javaString(configuration.datawayUrl)};`,
    `    static final String CLIENT_TOKEN = ${javaString(configuration.clientToken)};`,
    `    static final String ANDROID_RUM_APP_ID = ${javaString(configuration.androidAppId)};`,
    `    static final String SERVICE_NAME = ${javaString(configuration.serviceName)};`,
    `    static final String ENV = ${javaString(configuration.env)};`,
    `    static final boolean DEBUG = ${configuration.debug};`,
    '',
    '    private HybridSampleEnvironment() {}',
    '}',
    '',
  ].join('\n');
}

function renderIOSConfiguration(configuration) {
  return [
    '// Generated by npm run sample:configure. Contains local credentials; do not commit.',
    '#import <Foundation/Foundation.h>',
    '',
    `static NSString * const FTHybridSampleDatakitURL = ${objectiveCString(configuration.datakitUrl)};`,
    `static NSString * const FTHybridSampleDatawayURL = ${objectiveCString(configuration.datawayUrl)};`,
    `static NSString * const FTHybridSampleClientToken = ${objectiveCString(configuration.clientToken)};`,
    `static NSString * const FTHybridSampleIOSRumAppID = ${objectiveCString(configuration.iosAppId)};`,
    `static NSString * const FTHybridSampleServiceName = ${objectiveCString(configuration.serviceName)};`,
    `static NSString * const FTHybridSampleEnv = ${objectiveCString(configuration.env)};`,
    `static const BOOL FTHybridSampleDebug = ${configuration.debug ? 'YES' : 'NO'};`,
    '',
  ].join('\n');
}

function javaString(value) {
  return value === undefined ? 'null' : JSON.stringify(value).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');
}

function objectiveCString(value) {
  if (value === undefined) return 'nil';
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r');
  return `@"${escaped}"`;
}

function readOption(name) {
  const argumentsList = process.argv.slice(2);
  const exactIndex = argumentsList.indexOf(name);
  if (exactIndex >= 0) {
    const value = argumentsList[exactIndex + 1];
    if (!value || value.startsWith('--')) fail(`Missing value for ${name}.`);
    return value;
  }
  const prefix = `${name}=`;
  const inline = argumentsList.find((argument) => argument.startsWith(prefix));
  return inline ? inline.slice(prefix.length) : undefined;
}

function readRelativeDirectoryOption(name, fallback) {
  const value = readOption(name) || fallback;
  const normalized = path.normalize(value);
  if (path.isAbsolute(normalized) || normalized === '..' || normalized.startsWith(`..${path.sep}`)) {
    fail(`${name} must stay inside --output-root.`);
  }
  return normalized;
}

function optional(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function parseBoolean(value, fallback) {
  if (value === undefined) return fallback;
  if (value === 'true') return true;
  if (value === 'false') return false;
  fail('SAMPLE_DEBUG must be true or false.');
}

function fail(message) {
  process.stderr.write(`[cocos-sdk-sample] ${message}\n`);
  process.exit(1);
}
